name: shortuuid
description: Generate short uuid (shorter version of 32 bit Guid). It will be useful if you need unque id that is in shorter format.
version: 2.1.1
author: Koumei Deng
homepage: https://github.com/coolmate/shortuuid
repository: https://github.com/coolmate/shortuuid

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  uuid: ^2.1.0

dev_dependencies:
  test: any